#title: AVERtek # your name photo (or website title) here
logo1: "images/BAHAY-LOGO-leaf-green-gold.png? raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <h1 style="color:#215732;"><p style="text-align:center;"><b>MEANS HOME</h1></b></p>
  <h2 style="color:#A28D5B;"><em><p style="text-align:center;"><b>NEW RESIDENTIAL REFERRAL PROGRAM</h2></em></b></p>
  <h3><p style="text-align:center;"<b>RESIDENT: Share this link with a friend, They take a tour and get a VIP gift; They move in and you get $500 off 1 months rent!</h3></b></p>
  <br><br> 
  <h3><p style="text-align:center;"<b>FRIEND: Click link below, Sign up for a Tour & List who referred you in the Comments/Special Code Box to recieve a VIP Gift & Special Move-In Discount!</h3></b></p>
  <h3><a href="https://alexanbahay.com/gallery/video/?utm_source=AVERtek&utm_medium=AR" onclick="getOutboundLink('https://alexanbahay.com/gallery/video/?utm_source=AVERtek&utm_medium=AR'); return false;"<b><p style="text-align:center;"> VIEW: LUXURY LIVING</h3></b></p></a> 
  <br>
  <h3><a href="https://alexanbahay.com/special/?utm_source=AVERtek&utm_medium=AR" onclick="getOutboundLink('https://alexanbahay.com/special/?utm_source=AVERtek&utm_medium=AR'); return false;"<b><p style="text-align:center;"> SIGN-UP: LIST REFERRAL'S NAME GET VIP TOUR & FREE GIFT</h3></b></p></a>
  <br>
  <h3 style="color:#A28D5B;"><em><p style="text-align:center;"><b>50% Off All Summer Long</h2></em></b></p>
  
theme: jekyll-theme-minimal
# Google Analytics
google_analytics: UA-188164724-2 
